Bump version v0.6.0.1
arqma/arqma pull request #201
Opened 2020-01-07 14:07 UTC by ArqTras

Copyrights Update

2020-01-16 09:35 UTC, malbit requested changes

2020-01-16 09:35 UTC, malbit commented on README.md
> +`$ cd arqma && git checkout release-v0.6.0.1`
It will not be new release but only new TAG inside release-v0.6.0 branch. So that change is not needed

2020-01-16 09:35 UTC, malbit commented on README.md
> +	`cd arqma && git checkout release-v0.6.0.1`
same as above

2020-01-16 10:06 UTC, ArqTras commented on README.md
> +	`cd arqma && git checkout release-v0.6.0.1`
fixed

2020-02-16 02:07 UTC, malbit approved these changes

2020-02-16 02:08 UTC, merged