ZMQ let the testing begin
arqma/arqma pull request #210
Opened 2020-03-23 16:22 UTC by muscleman

2020-03-23 16:28 UTC, ArqTras commented
License and other stuff to add :D

2020-03-23 17:25 UTC, ArqTras submitted a review, later dismissed

2020-03-23 21:58 UTC, malbit requested changes
I will do tests later on.
License infos need to be fixed.

2020-03-23 21:58 UTC, malbit commented on src/arqma_mq/INotifier.h
> +// Parts of this file are copyright (c) 2014-2020 The Arqma Network
Should be “2014-2020, The Monero Project“ instead

2020-03-23 21:58 UTC, malbit commented on src/arqma_mq/INotifier.h
> +// Parts of this file are copyright (c) 2020-2021 Gary Rusher
are we in the future already??
That line is not needed cus Copyright are already stated on top of the file.

2020-03-23 21:58 UTC, malbit commented on src/arqma_mq/arqmaMQ.cpp
> +// Parts of this file are copyright (c) 2014-2020 The Arqma Network
Same as above file :)

2020-03-23 21:58 UTC, malbit commented on src/arqma_mq/arqmaMQ.cpp
> +// Parts of this file are copyright (c) 2020-2021 Gary Rusher
same as above file :)

2020-03-23 21:58 UTC, malbit commented on src/arqma_mq/arqmaMQ.h
> +// Parts of this file are copyright (c) 2014-2020 The Arqma Network
Same as above.

2020-03-23 21:58 UTC, malbit commented on src/arqma_mq/arqmaMQ.h
> +// Parts of this file are copyright (c) 2020-2021 Gary Rusher
Same as above.

2020-03-23 21:58 UTC, malbit commented on src/arqma_mq/utils.hpp
> +// Parts of this file are copyright (c) 2014-2020 The Arqma Network
As above.

2020-03-23 21:58 UTC, malbit commented on src/arqma_mq/utils.hpp
> +// Parts of this file are copyright (c) 2020-2021 Gary Rusher
As above

2020-03-24 21:07 UTC, ArqTras approved these changes
Looks correct and functional.
Additional improvements can be added in future using this as basic.

2020-03-27 09:57 UTC, ArqTras approved these changes

2020-03-27 10:00 UTC, ArqTras approved these changes

2020-03-28 20:30 UTC, malbit approved these changes

2020-03-28 20:30 UTC, merged