add additional seed node
arqma/arqma pull request #303
Opened 2021-12-02 04:48 UTC by BigslimVdub

Add additional seed node and update Copywrite year to 2022

2021-12-02 09:26 UTC, malbit requested changes
Did you forgot about comas ??

2021-12-02 09:26 UTC, malbit commented on src/cryptonote_config.h
>      "164.68.123.118"
coma required at next to last line :)

2021-12-02 09:26 UTC, malbit commented on src/cryptonote_config.h
>      "144.217.242.16"
Same as above

2021-12-06 02:25 UTC, BigslimVdub commented
Updated

2021-12-06 02:28 UTC, malbit approved these changes

2021-12-06 02:28 UTC, merged